
name: Create AWS IAM User

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
      

jobs:
  # condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tfc_team_token }}
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -input=false
      
      - name: Terraform Apply
        if:  success() && github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
        run: terraform apply -auto-approve

      # - name: Terraform destroy
      #   run: terraform destroy -auto-approve

