name: Create AWS IAM User

on:
  push:
      paths: 
      - 'create-iam-user/main.tf' # Trigger only when changes are made in the create-user directory


jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.tfc_team_token }}

      - name: cd
        run: |
            cd create-iam-user/
      
      - name: Terraform Init
        run: terraform init -chdir=create-iam-user

      # - name: Terraform plan
      #   run: terraform plan -input=false
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -chdir=create-iam-user

